name: Build

'on':
  workflow_dispatch:

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.10.0'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: |
          python -m pip install build "pyinstaller>=6.15" pyinstaller-hooks-contrib
          python -m pip install "passlib[bcrypt]" bcrypt
          python -m pip install .
      - name: Detect paths
        run: |
          script=$(python - <<'PY'
          import shutil, pathlib
          p = shutil.which('open-webui')
          if not p:
              raise SystemExit('entry script not found')
          print(pathlib.Path(p))
          PY
                    )
                    echo "OWUI_SCRIPT=$script" >> $GITHUB_ENV
                    mig=$(python - <<'PY'
          import pathlib, open_webui
          print((pathlib.Path(open_webui.__file__).resolve().parent / "internal" / "migrations").as_posix())
          PY
          )
          echo "OWUI_MIG=$mig" >> $GITHUB_ENV
      - name: PyInstaller
        run: |
          pyinstaller "$OWUI_SCRIPT" \
            --name open-webui \
            --onefile \
            --distpath dist-bin \
            --workpath build-bin \
            --clean \
            --noconfirm \
            --strip \
            --log-level=WARN \
            --copy-metadata open_webui \
            --copy-metadata passlib \
            --copy-metadata uvicorn \
            --hidden-import=passlib.handlers.bcrypt \
            --hidden-import=bcrypt \
            --hidden-import=uvicorn.logging \
            --collect-submodules passlib.handlers \
            --collect-submodules open_webui.internal.migrations \
            --add-data "$OWUI_MIG:open_webui/internal/migrations" \
            --add-data CHANGELOG.md:open_webui \
            --collect-data open_webui
      - run: du -sh dist-bin || true
      - uses: actions/upload-artifact@v4
        with:
          name: open-webui-macos
          path: dist-bin/*
